# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/samuele/CLionProjects/RadTrack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/samuele/CLionProjects/RadTrack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/samuele/CLionProjects/RadTrack/CMakeFiles /home/samuele/CLionProjects/RadTrack//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/samuele/CLionProjects/RadTrack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RadTrack

# Build rule for target.
RadTrack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RadTrack
.PHONY : RadTrack

# fast build rule for target.
RadTrack/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/build
.PHONY : RadTrack/fast

src/close_window_callback.o: src/close_window_callback.cpp.o
.PHONY : src/close_window_callback.o

# target to build an object file
src/close_window_callback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/close_window_callback.cpp.o
.PHONY : src/close_window_callback.cpp.o

src/close_window_callback.i: src/close_window_callback.cpp.i
.PHONY : src/close_window_callback.i

# target to preprocess a source file
src/close_window_callback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/close_window_callback.cpp.i
.PHONY : src/close_window_callback.cpp.i

src/close_window_callback.s: src/close_window_callback.cpp.s
.PHONY : src/close_window_callback.s

# target to generate assembly for a file
src/close_window_callback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/close_window_callback.cpp.s
.PHONY : src/close_window_callback.cpp.s

src/engine/sources/engine.o: src/engine/sources/engine.cpp.o
.PHONY : src/engine/sources/engine.o

# target to build an object file
src/engine/sources/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine.cpp.o
.PHONY : src/engine/sources/engine.cpp.o

src/engine/sources/engine.i: src/engine/sources/engine.cpp.i
.PHONY : src/engine/sources/engine.i

# target to preprocess a source file
src/engine/sources/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine.cpp.i
.PHONY : src/engine/sources/engine.cpp.i

src/engine/sources/engine.s: src/engine/sources/engine.cpp.s
.PHONY : src/engine/sources/engine.s

# target to generate assembly for a file
src/engine/sources/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine.cpp.s
.PHONY : src/engine/sources/engine.cpp.s

src/engine/sources/engine_input.o: src/engine/sources/engine_input.cpp.o
.PHONY : src/engine/sources/engine_input.o

# target to build an object file
src/engine/sources/engine_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine_input.cpp.o
.PHONY : src/engine/sources/engine_input.cpp.o

src/engine/sources/engine_input.i: src/engine/sources/engine_input.cpp.i
.PHONY : src/engine/sources/engine_input.i

# target to preprocess a source file
src/engine/sources/engine_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine_input.cpp.i
.PHONY : src/engine/sources/engine_input.cpp.i

src/engine/sources/engine_input.s: src/engine/sources/engine_input.cpp.s
.PHONY : src/engine/sources/engine_input.s

# target to generate assembly for a file
src/engine/sources/engine_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine_input.cpp.s
.PHONY : src/engine/sources/engine_input.cpp.s

src/engine/sources/engine_time.o: src/engine/sources/engine_time.cpp.o
.PHONY : src/engine/sources/engine_time.o

# target to build an object file
src/engine/sources/engine_time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine_time.cpp.o
.PHONY : src/engine/sources/engine_time.cpp.o

src/engine/sources/engine_time.i: src/engine/sources/engine_time.cpp.i
.PHONY : src/engine/sources/engine_time.i

# target to preprocess a source file
src/engine/sources/engine_time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine_time.cpp.i
.PHONY : src/engine/sources/engine_time.cpp.i

src/engine/sources/engine_time.s: src/engine/sources/engine_time.cpp.s
.PHONY : src/engine/sources/engine_time.s

# target to generate assembly for a file
src/engine/sources/engine_time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/engine_time.cpp.s
.PHONY : src/engine/sources/engine_time.cpp.s

src/engine/sources/gl_helper.o: src/engine/sources/gl_helper.cpp.o
.PHONY : src/engine/sources/gl_helper.o

# target to build an object file
src/engine/sources/gl_helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/gl_helper.cpp.o
.PHONY : src/engine/sources/gl_helper.cpp.o

src/engine/sources/gl_helper.i: src/engine/sources/gl_helper.cpp.i
.PHONY : src/engine/sources/gl_helper.i

# target to preprocess a source file
src/engine/sources/gl_helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/gl_helper.cpp.i
.PHONY : src/engine/sources/gl_helper.cpp.i

src/engine/sources/gl_helper.s: src/engine/sources/gl_helper.cpp.s
.PHONY : src/engine/sources/gl_helper.s

# target to generate assembly for a file
src/engine/sources/gl_helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/gl_helper.cpp.s
.PHONY : src/engine/sources/gl_helper.cpp.s

src/engine/sources/screen.o: src/engine/sources/screen.cpp.o
.PHONY : src/engine/sources/screen.o

# target to build an object file
src/engine/sources/screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/screen.cpp.o
.PHONY : src/engine/sources/screen.cpp.o

src/engine/sources/screen.i: src/engine/sources/screen.cpp.i
.PHONY : src/engine/sources/screen.i

# target to preprocess a source file
src/engine/sources/screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/screen.cpp.i
.PHONY : src/engine/sources/screen.cpp.i

src/engine/sources/screen.s: src/engine/sources/screen.cpp.s
.PHONY : src/engine/sources/screen.s

# target to generate assembly for a file
src/engine/sources/screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/engine/sources/screen.cpp.s
.PHONY : src/engine/sources/screen.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/sources/engine_logger.o: src/utils/sources/engine_logger.cpp.o
.PHONY : src/utils/sources/engine_logger.o

# target to build an object file
src/utils/sources/engine_logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/engine_logger.cpp.o
.PHONY : src/utils/sources/engine_logger.cpp.o

src/utils/sources/engine_logger.i: src/utils/sources/engine_logger.cpp.i
.PHONY : src/utils/sources/engine_logger.i

# target to preprocess a source file
src/utils/sources/engine_logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/engine_logger.cpp.i
.PHONY : src/utils/sources/engine_logger.cpp.i

src/utils/sources/engine_logger.s: src/utils/sources/engine_logger.cpp.s
.PHONY : src/utils/sources/engine_logger.s

# target to generate assembly for a file
src/utils/sources/engine_logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/engine_logger.cpp.s
.PHONY : src/utils/sources/engine_logger.cpp.s

src/utils/sources/logger.o: src/utils/sources/logger.cpp.o
.PHONY : src/utils/sources/logger.o

# target to build an object file
src/utils/sources/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/logger.cpp.o
.PHONY : src/utils/sources/logger.cpp.o

src/utils/sources/logger.i: src/utils/sources/logger.cpp.i
.PHONY : src/utils/sources/logger.i

# target to preprocess a source file
src/utils/sources/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/logger.cpp.i
.PHONY : src/utils/sources/logger.cpp.i

src/utils/sources/logger.s: src/utils/sources/logger.cpp.s
.PHONY : src/utils/sources/logger.s

# target to generate assembly for a file
src/utils/sources/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/logger.cpp.s
.PHONY : src/utils/sources/logger.cpp.s

src/utils/sources/utils_types.o: src/utils/sources/utils_types.cpp.o
.PHONY : src/utils/sources/utils_types.o

# target to build an object file
src/utils/sources/utils_types.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/utils_types.cpp.o
.PHONY : src/utils/sources/utils_types.cpp.o

src/utils/sources/utils_types.i: src/utils/sources/utils_types.cpp.i
.PHONY : src/utils/sources/utils_types.i

# target to preprocess a source file
src/utils/sources/utils_types.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/utils_types.cpp.i
.PHONY : src/utils/sources/utils_types.cpp.i

src/utils/sources/utils_types.s: src/utils/sources/utils_types.cpp.s
.PHONY : src/utils/sources/utils_types.s

# target to generate assembly for a file
src/utils/sources/utils_types.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RadTrack.dir/build.make CMakeFiles/RadTrack.dir/src/utils/sources/utils_types.cpp.s
.PHONY : src/utils/sources/utils_types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RadTrack"
	@echo "... src/close_window_callback.o"
	@echo "... src/close_window_callback.i"
	@echo "... src/close_window_callback.s"
	@echo "... src/engine/sources/engine.o"
	@echo "... src/engine/sources/engine.i"
	@echo "... src/engine/sources/engine.s"
	@echo "... src/engine/sources/engine_input.o"
	@echo "... src/engine/sources/engine_input.i"
	@echo "... src/engine/sources/engine_input.s"
	@echo "... src/engine/sources/engine_time.o"
	@echo "... src/engine/sources/engine_time.i"
	@echo "... src/engine/sources/engine_time.s"
	@echo "... src/engine/sources/gl_helper.o"
	@echo "... src/engine/sources/gl_helper.i"
	@echo "... src/engine/sources/gl_helper.s"
	@echo "... src/engine/sources/screen.o"
	@echo "... src/engine/sources/screen.i"
	@echo "... src/engine/sources/screen.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/sources/engine_logger.o"
	@echo "... src/utils/sources/engine_logger.i"
	@echo "... src/utils/sources/engine_logger.s"
	@echo "... src/utils/sources/logger.o"
	@echo "... src/utils/sources/logger.i"
	@echo "... src/utils/sources/logger.s"
	@echo "... src/utils/sources/utils_types.o"
	@echo "... src/utils/sources/utils_types.i"
	@echo "... src/utils/sources/utils_types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

